name       : gnome-boxes
version    : 3.20.3
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.20/gnome-boxes-3.20.3.tar.xz : cd1e86e6bea4752d2d4175c0a70c841d9740e3968a6f98e06aca30da12b92a94
license    : GPL-2.0
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-1.0)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
