name       : gnome-boxes
version    : 3.22.4
release    : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-boxes/3.22/gnome-boxes-3.22.4.tar.xz : 585a1c292010ebb479cb60e02621d01d450f84cdad82a61b7ce58a0218e1cff2
license    : GPL-2.0
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-1.0)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
