name       : gnome-boxes
version    : 3.38.2
release    : 33
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-boxes.git : v3.38.2
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(winpr2)
    - pkgconfig(vte-2.91)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
    - spice
    - virglrenderer
setup      : |
    # Under no circumstances should 0001-Eliminate-use-of-libhandy.patch be removed. If it fails to apply, rebase.
    %patch -p1 < $pkgfiles/0001-Eliminate-use-of-libhandy.patch
    %patch -p1 < $pkgfiles/0001-Ensure-VMs-with-nvram-are-removable.patch
    %meson_configure -Ddistributor_name=Solus -Dovirt=false
build      : |
    %ninja_build
install    : |
    %ninja_install
