name       : gnome-boxes
version    : 3.24.0
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-boxes/3.24/gnome-boxes-3.24.0.tar.xz : 7495ea7184b6ef650033daf6941328b785b22e522e8142b9d190575d215dec49
license    : GPL-2.0
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-1.0)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
