name       : gnome-boxes
version    : 3.18.1
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.18/gnome-boxes-3.18.1.tar.xz : 0235d7f76cf3faa3889b302c743d608759e84506657ed4e374592c39f768fb2b
license    : GPL-2.0
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - itstool
    - intltool
    - vala
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libusb-1.0) 
    - pkgconfig(libosinfo-1.0) 
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-1.0)
patterns   :
    - /usr/share/man
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
