name       : gnome-boxes
version    : 3.26.1
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.26/gnome-boxes-3.26.1.tar.xz : fc0d4479b076393caeeab22d9ae3247503b9eb15b6bfe8fdfab2f2435051fa58
license    : GPL-2.0
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-2.0)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
