name       : gnome-boxes
version    : 3.32.0.2
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.32/gnome-boxes-3.32.0.2.tar.xz : 93ebeb05034b69683bc7b944f84a138a667db294fb7e8170ef0fd8b956e86988
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(winpr2)
    - pkgconfig(vte-2.91)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
setup      : |
    %patch -p1 < $pkgfiles/appdata-Keep-the-app-id.patch
    %meson_configure -Ddistributor_name=Solus -Dovirt=false
build      : |
    %ninja_build
install    : |
    %ninja_install
