name       : gnome-boxes
version    : 3.36.6
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.36/gnome-boxes-3.36.6.tar.xz : ef1646e81bfff10ba94aefcbe77eec4aa3f78096d4802f18539761dc41e26c30
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(winpr2)
    - pkgconfig(vte-2.91)
    - itstool
    - intltool
    - tracker-devel # Change to pkgconfig(tracker-sparql-3.0) after upgrade push
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
    - spice
    - virglrenderer
setup      : |
    %patch -p1 < $pkgfiles/0001-media-manager-Port-to-tracker-3.patch
    %meson_configure -Ddistributor_name=Solus -Dovirt=false
build      : |
    %ninja_build
install    : |
    %ninja_install
