name       : gnome-boxes
version    : 3.34.3
release    : 21
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.34/gnome-boxes-3.34.3.tar.xz : 8a8fa5b13d14ff75b0224702ea6ec350ae43b801bc89207ffe1415b3f4c3f0c7
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(winpr2)
    - pkgconfig(vte-2.91)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
    - spice
    - virglrenderer
setup      : |
    %meson_configure -Ddistributor_name=Solus -Dovirt=false
build      : |
    %ninja_build
install    : |
    %ninja_install
