name       : gnome-boxes
version    : 3.28.5
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-boxes/3.28/gnome-boxes-3.28.5.tar.xz : f5de0987c2f4f710cc6a7a0333ab4db2f9253aeb2dab9c0e3ddc867e758d38fc
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
setup      : |
    %patch -p1 < $pkgfiles/0001-build-Unbreak-the-icon-installation-in-gnome-3-28.patch
    %meson_configure -Ddistributor_name=Solus -Dovirt=false
build      : |
    %ninja_build
install    : |
    %ninja_install
